networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.216/29
          gateway: 172.21.0.217

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /ruta/a/tu/directorio/postgres
      o: bind
  zabbix_server_data:
    driver: local
    driver_opts:
      type: none
      device: /ruta/a/tu/directorio/zabbix_server
      o: bind

services:
  postgres-server:
    image: postgres:latest
    container_name: postgres-server
    environment:
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix_pwd"
      POSTGRES_DB: "zabbix"
    networks:
      zabbix-net:
        ipv4_address: 172.21.0.218
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  zabbix-server-pgsql:
    image: zabbix/zabbix-server-pgsql:alpine-7.2-latest
    container_name: zabbix-server-pgsql
    environment:
      DB_SERVER_HOST: "postgres-server"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix_pwd"
      POSTGRES_DB: "zabbix"
    depends_on:
      - postgres-server
    networks:
      zabbix-net:
        ipv4_address: 172.21.0.219
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    ports:
      - "10051:10051"
    restart: unless-stopped

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.2-latest
    container_name: zabbix-web-nginx-pgsql
    environment:
      ZBX_SERVER_HOST: "zabbix-server-pgsql"
      DB_SERVER_HOST: "postgres-server"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix_pwd"
      POSTGRES_DB: "zabbix"
    depends_on:
      - zabbix-server-pgsql
    networks:
      zabbix-net:
        ipv4_address: 172.21.0.220
    ports:
      - "80:8080"
    restart: unless-stopped
